import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-brand-bg">
      <Navbar />

      <main className="pt-24 pb-20 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto">
          <h1 className="font-heading font-bold text-3xl sm:text-4xl text-white mb-8">
            Terms of <span className="gradient-text">Service</span>
          </h1>

          <div className="prose prose-invert max-w-none space-y-6 font-body text-brand-muted">
            <p className="text-sm">Last updated: February 2026</p>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing or using BrandSnap (&quot;the Service&quot;), operated by Automatik.studio, you agree to be bound by
                these Terms of Service. If you do not agree, please do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">2. Service Description</h2>
              <p>
                BrandSnap is an AI-powered brand identity kit generator. The Service uses artificial intelligence to
                generate color palettes, font pairings, logo concepts, brand voice guidelines, and social media templates
                based on user input.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">3. User Responsibilities</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>You must provide accurate business information for brand kit generation</li>
                <li>You are responsible for how you use the generated brand assets</li>
                <li>You must not use the Service for unlawful purposes</li>
                <li>You must not attempt to reverse-engineer or abuse the Service</li>
              </ul>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">4. Intellectual Property</h2>
              <p>
                Brand kits generated through the Service are provided for your use. You retain rights to use the generated
                content for your business purposes. However, similar outputs may be generated for other users due to the
                nature of AI generation. The BrandSnap name, logo, and Service design remain the property of Automatik.studio.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">5. Pricing & Payments</h2>
              <p>
                BrandSnap offers both free and paid tiers. Paid plans are one-time purchases unless otherwise stated.
                All sales are final. We reserve the right to modify pricing at any time.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">6. AI-Generated Content</h2>
              <p>
                Brand kits are generated by artificial intelligence. While we strive for quality and relevance,
                we cannot guarantee that all generated content will be perfectly suited to your needs. Generated
                content should be reviewed and may require professional refinement. Font and color recommendations
                are suggestions and should be verified for your specific use case.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">7. Limitation of Liability</h2>
              <p>
                BrandSnap and Automatik.studio are provided &quot;as is&quot; without warranties of any kind. We shall not be
                liable for any indirect, incidental, or consequential damages arising from your use of the Service.
                Our total liability shall not exceed the amount you paid for the Service.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">8. Service Availability</h2>
              <p>
                We strive to maintain high availability but do not guarantee uninterrupted access. The Service may
                be temporarily unavailable for maintenance, updates, or due to circumstances beyond our control.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">9. Termination</h2>
              <p>
                We reserve the right to terminate or suspend access to the Service at our discretion, without notice,
                for conduct that we believe violates these Terms or is harmful to other users or the Service.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">10. Changes to Terms</h2>
              <p>
                We may revise these Terms at any time. Continued use of the Service after changes constitutes
                acceptance of the updated Terms.
              </p>
            </section>

            <section>
              <h2 className="font-heading font-semibold text-xl text-white mt-8 mb-4">11. Contact</h2>
              <p>
                For questions regarding these Terms, contact us at:{" "}
                <a href="mailto:automatikstudiomail@gmail.com" className="text-brand-fuchsia hover:text-brand-yellow transition-colors">
                  automatikstudiomail@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}
